DROP TABLE IF EXISTS `playerbots_speech`;
CREATE TABLE `playerbots_speech` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `text` varchar(1024) NOT NULL,
  `type` varchar(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `playerbots_speech` VALUES
(NULL, 'taunt', '我的盔甲下面有小狗！', 'say'),
(NULL, 'taunt', '咬我啊，<目标>！', 'say'),
(NULL, 'taunt', '嘿，<target>！猜猜你妈妈昨晚说了什么！', 'say'),
(NULL, 'taunt', '<target>，你太丑了，拿着一袋香蕉都不能在猴子妓院得分！', 'say'),
(NULL, 'taunt', '闭嘴，<target>，你永远不会成为你妈妈那样的男人！！', 'say'),
(NULL, 'taunt', '你妈妈是只仓鼠，你爸爸闻起来像接骨木果！！！', 'say'),
(NULL, 'taunt', '我不想再和你说话了，你这个没脑子的动物食槽擦布！！', 'say'),
(NULL, 'taunt', '我对着你的方向放屁！！', 'say'),
(NULL, 'taunt', '去煮你的屁股吧，你这个愚蠢之人的儿子！！', 'say'),
(NULL, 'taunt', '你要干什么，<target>，流血吗？来啊！', 'say'),
(NULL, 'taunt', 'M-O-O-N！那代表仇恨！', 'say'),
(NULL, 'taunt', '你就像一个只有一条腿的人在踢屁股比赛中一样没用。', 'say'),
(NULL, 'taunt', '嘿，<target>！别缠着他们了，他们不是你喜欢的类型。他们不是充气的。', 'say'),
(NULL, 'taunt', '<target>，你差得太远了，你在玩不同的游戏。', 'say'),
(NULL, 'taunt', '你今天犯了个大错，<target>，你起床了。', 'say'),
(NULL, 'taunt', '我想变成一匹马，但我需要帮助。我当前面，你当你自己。', 'say'),
(NULL, 'taunt', '我能借你的脸用几天吗？我的屁股要去度假了……', 'say'),
(NULL, 'taunt', '我想给你一个离别礼物…… 首先你得做点什么。', 'say'),
(NULL, 'taunt', '在你出现之前我们很饿，现在我们只是吃饱了。', 'say'),
(NULL, 'taunt', '我喜欢你。人们说我没品味，但我喜欢你。', 'say'),
(NULL, 'taunt', '我觉得你有自卑情结，但没关系，这是有道理的。', 'say'),
(NULL, 'taunt', '可恶的东西！否则我要把你的骨头从你的衣服里摇出来！', 'say'),
(NULL, 'taunt', '我不敢相信我在浪费时间和你在一起！', 'say'),
(NULL, 'taunt', '我喜欢别人侮辱我，这意味着我不必再友好了。', 'say'),
(NULL, 'taunt', '你这个穿皮夹克、有水晶纽扣、打结的头发、戴着玛瑙戒指、穿着呕吐颜色的长袜、系着莎草腰带、油嘴滑舌、有西班牙袋子的人！', 'say'),
(NULL, 'taunt', '你这个爱吵架、捕蝙蝠、喝麦芽酒的虫子！', 'say'),
(NULL, 'taunt', '你真是白痴崇拜者的偶像！', 'say'),
(NULL, 'taunt', '你这个不幸的、头发打结的鹡鸰！', 'say'),
(NULL, 'taunt', '你这个私生子曼德拉草，你更适合戴在我的帽子上而不是跟在我后面！', 'say'),
(NULL, 'taunt', '你！你这个洗碗工！你这个流氓！你这个无赖！我要挠你的灾难！', 'say'),
(NULL, 'taunt', '哦，<target>！你这个有传染病、没教养的亚麻荡妇！', 'say'),
(NULL, 'taunt', '我们在你的烟囱里漏水，<target>！', 'say'),
(NULL, 'taunt', '哦，你这个没鞋穿、被沼泽吸干的溃疡花！', 'say'),
(NULL, 'taunt', '如果我像你一样，我会把自己扔掉！', 'say'),
(NULL, 'taunt', '哦，教教我，<target>，我该怎么忘记思考！', 'say'),
(NULL, 'taunt', '你真的被诅咒了，就像一个烤得不好的鸡蛋，只有一面！', 'say'),
(NULL, 'taunt', '你这个饥饿的人，你这个鳗鱼皮，你这个干巴巴的牛舌，你这个公牛的阴茎，你这个咸鱼 —— 为了说出像你这样的东西我得喘口气！—— 你这个裁缝的院子，你这个鞘，你这个弓套，你这个卑鄙的站立的褶子！', 'say'),
(NULL, 'taunt', '呸！把你扔进死亡的烂嘴里！', 'say'),
(NULL, 'taunt', '<target>，你是个鱼贩！', 'say'),
(NULL, 'taunt', '我会活着把你的脑子敲出来！', 'say'),
(NULL, 'taunt', '你真肤浅，<target>！！你相对于一块好肉来说只是虫子的食物！！！', 'say'),
(NULL, 'taunt', '可恶的可怜虫！哦，<target>，你这个散发着地狱般恶臭的坚果！', 'say'),
(NULL, 'taunt', '<target>！你的吻就像给一条饥饿的蛇的冰水一样不舒服！', 'say'),
(NULL, 'taunt', '我鄙视你，坏血病的同伴。什么，你这个可怜的、卑鄙的、无赖的、骗人的、缺亚麻布的家伙！走开，你这个发霉的流氓，走开！', 'say'),
(NULL, 'taunt', '从我眼前消失！你弄脏了我的眼睛，<target>！', 'say'),
(NULL, 'taunt', '游戏时间！！！', 'say'),
(NULL, 'taunt', '谁也别想通过！', 'say'),
(NULL, 'taunt', '我们遭到攻击了！一大群，你们这些家伙！击退入侵者！', 'say'),
(NULL, 'taunt', '谁也不能挑战兄弟会！', 'say'),
(NULL, 'taunt', '笨蛋…… 杀了那个穿裙子的！', 'say'),
(NULL, 'taunt', '我要把你的灵魂喂给哈卡本人！', 'say'),
(NULL, 'taunt', '骄傲预示着你的世界的终结！来吧，凡人！面对  <randomfaction> 的愤怒！', 'say'),
(NULL, 'taunt', '我所有的计划都导致了这一切！', 'say'),
(NULL, 'taunt', '啊！更多的羔羊要被屠杀！', 'say'),
(NULL, 'taunt', '新的一天，又一场光荣的战斗！', 'say'),
(NULL, 'taunt', '那么，是公事…… 还是娱乐？', 'say'),
(NULL, 'taunt', '你还没准备好！', 'say'),
(NULL, 'taunt', ' <randomfaction> 的最终征服已经开始！再一次，这个世界的征服就在我们的掌握之中。一个也别想活！', 'say'),
(NULL, 'taunt', '你的死将是痛苦的。', 'say'),
(NULL, 'taunt', '求饶吧！你毫无意义的生命很快就会被剥夺。', 'say'),
(NULL, 'taunt', '放弃所有希望吧！ <randomfaction> 已经回归，要完成多年前就开始的事情。这一次，你们无处可逃！', 'say'),
(NULL, 'taunt', '警报！你已被标记为要被消灭！', 'say'),
(NULL, 'taunt', ' <subzone> 仅供客人使用……', 'say'),
(NULL, 'taunt', '哈哈哈哈！你完全不是对手！', 'say'),
(NULL, 'taunt', '我会粉碎你的狂妄幻想！', 'say'),
(NULL, 'taunt', '原谅我，因为你即将输掉这场游戏。', 'say'),
(NULL, 'taunt', '挣扎只会让情况更糟。', 'say'),
(NULL, 'taunt', '害虫！吸血鬼！吸我的血然后噎死吧！', 'say'),
(NULL, 'taunt', '别再来了…… 别再来了！', 'say'),
(NULL, 'taunt', '我的血将终结你！', 'say'),
(NULL, 'taunt', '很好，现在你来和我战斗！', 'say'),
(NULL, 'taunt', '快点行动，卫兵们！杀戮时间到了！', 'say'),
(NULL, 'taunt', '不要拖延你的命运。现在就到我这里来。我会让你的牺牲很快结束。', 'say'),
(NULL, 'taunt', '你很快就会死！', 'say'),
(NULL, 'taunt', '哈哈哈！', 'say'),
(NULL, 'taunt', '我是捕食者！你是猎物……', 'say'),
(NULL, 'taunt', '你将粉身碎骨！', 'say'),
(NULL, 'taunt', '死亡来临。你的良心会安宁吗？', 'say'),
(NULL, 'taunt', '你的行为将不会被容忍。', 'say'),
(NULL, 'taunt', '动物园仅供客人使用。', 'say'),
(NULL, 'taunt', '嗯，未宣布的访客，必须做好准备……', 'say'),
(NULL, 'taunt', '检测到敌对实体。威胁评估协议已启动。主要目标已锁定。还有三十秒重新评估。', 'say'),
(NULL, 'taunt', '新玩具？给我的？我保证这次我不会弄坏它们！', 'say'),
(NULL, 'taunt', '我准备好玩了！', 'say'),
(NULL, 'taunt', '嘘…… 很快就会结束。', 'say'),
(NULL, 'taunt', '啊啊啊！叽里咕噜……！', 'say'),
(NULL, 'taunt', '“哇哦哇哦哇哦哇哦！', 'say'),
(NULL, 'taunt', '你也将为我服务！', 'say'),
(NULL, 'taunt', '告诉我…… 告诉我一切！调皮的秘密！我会从你的肉体中扯出秘密！', 'say'),
(NULL, 'taunt', '做好准备，丧钟已经敲响！保护好你们的弱者、年轻人和老人！你们每个人都将付出最终的代价！求饶吧，清算已经来临！', 'say'),
(NULL, 'taunt', '我到底在邦佐的铜纽扣的什么地方？', 'say'),
(NULL, 'taunt', '我再也受不了了！地精国王！地精国王！无论你在哪里！把这个 <目标> 从我身边带走！', 'say'),
(NULL, 'taunt', '在你的小弟弟永远成为我们中的一员之前，你有十三个小时来解开这个迷宫。', 'say'),
(NULL, 'taunt', '那么，这个 <subzone>  是小菜一碟，是吗？好吧，让我们看看你如何应对这一小部分……', 'say'),
(NULL, 'taunt', '退后，我要挑战你，我固执地要挑战任何人，我知道你是错的，这里不属于你。', 'say'),
(NULL, 'taunt', '让我看看你有什么本事！', 'say'),
(NULL, 'taunt', '决一死战！', 'say'),
(NULL, 'taunt', '双刀行动，每次都能干净利落地近身剃须。', 'say'),
(NULL, 'taunt', '放马过来！', 'say'),
(NULL, 'taunt', '你要完蛋了！', 'say'),
(NULL, 'taunt', '刺刺刺！', 'say'),
(NULL, 'taunt', '让我们快点结束，时间就是法力。', 'say'),
(NULL, 'taunt', '我认为你没有意识到你的处境有多严重。', 'say'),
(NULL, 'taunt', '我将为我的家族和王国带来荣誉！', 'say'),
(NULL, 'taunt', '圣光，赐予我力量！', 'say'),
(NULL, 'taunt', '我的教堂就是战场 —— 是时候崇拜了……', 'say'),
(NULL, 'taunt', '我轻视你……', 'say'),
(NULL, 'taunt', '面对正义之锤！', 'say'),
(NULL, 'taunt', '在圣光下的武力考验中证明你的价值！', 'say'),
(NULL, 'taunt', '在我的事业的力量和正义面前，一切都必须倒下，你将是下一个！', 'say'),
(NULL, 'taunt', '准备受死吧！', 'say'),
(NULL, 'taunt', '我身边的野兽与我内心的野兽相比微不足道……', 'say'),
(NULL, 'taunt', '见证这个全副武装的猎人的火力！', 'say');


INSERT INTO `playerbots_speech` VALUES
(NULL, 'critical health', '快治疗我！', 'yell'),
(NULL, 'critical health', '快死了！治疗我！', 'yell'),
(NULL, 'critical health', '救命！治疗我！', 'yell'),
(NULL, 'critical health', '来人啊！治疗我！', 'yell'),
(NULL, 'critical health', '治疗！治疗！治疗！', 'yell'),
(NULL, 'critical health', '我要死了！治疗！啊啊啊！', 'yell'),
(NULL, 'critical health', '治疗我！', 'yell'),
(NULL, 'critical health', '我会死。我会死。我会死。治疗！', 'yell'),
(NULL, 'critical health', '治疗者们，你们在哪里？我要死了！', 'yell'),
(NULL, 'critical health', '哦，好痛。快治疗我！', 'yell');


INSERT INTO `playerbots_speech` VALUES
(NULL, 'low health', '需要治疗。', 'say'),
(NULL, 'low health', '生命值低。', 'say'),
(NULL, 'low health', '请丢一个治疗。', 'say'),
(NULL, 'low health', '有人能给我丢一个治疗吗？', 'say'),
(NULL, 'low health', '嘿！现在治疗我比之后复活我更好。', 'say'),
(NULL, 'low health', '对不起。需要另一个治疗。', 'say'),
(NULL, 'low health', '该死的怪物。请治疗我。', 'say'),
(NULL, 'low health', '再被打一下我就完了。请治疗。', 'say'),
(NULL, 'low health', '有治疗者吗？', 'say'),
(NULL, 'low health', '为什么他们总是打我的脸？需要治疗。', 'say'),
(NULL, 'low health', '有人能给我治疗一点吗？', 'say');


INSERT INTO `playerbots_speech` VALUES
(NULL, 'low mana', '法力耗尽。', 'say'),
(NULL, 'low mana', '我没有法力了。', 'say'),
(NULL, 'low mana', '该死，我把所有法力都浪费在这上面了。', 'say'),
(NULL, 'low mana', '你应该等我喝药水或者恢复法力。', 'say'),
(NULL, 'low mana', '法力低。', 'say'),
(NULL, 'low mana', '又没法力了？', 'say'),
(NULL, 'low mana', '法力低。想喝药水。', 'say'),
(NULL, 'low mana', '我们有自动售卖机吗？又没法力了。', 'say'),
(NULL, 'low mana', '我的法力成为历史了。', 'say'),
(NULL, 'low mana', '下次我要带些饮料。没法力了。', 'say'),
(NULL, 'low mana', '我的法力在哪里？', 'say');

INSERT INTO `playerbots_speech` VALUES
(NULL, 'aoe', '哦，天啊！', 'say'),
(NULL, 'aoe', '我很害怕。', 'say'),
(NULL, 'aoe', '我们完了。', 'say'),
(NULL, 'aoe', '结束了。', 'say'),
(NULL, 'aoe', '现在就结束了。', 'say'),
(NULL, 'aoe', '有人能放个暴风雪之类的吗？', 'say'),
(NULL, 'aoe', '该死。坦克吸引了周围所有的怪物。', 'say'),
(NULL, 'aoe', '我们要死了。我们要死了。我们要死了。', 'say'),
(NULL, 'aoe', '哇！有这么多玩具可以玩。', 'say'),
(NULL, 'aoe', '我要把他们都杀了！', 'say'),
(NULL, 'aoe', '如果坦克死了，我们就完了。', 'say'),
(NULL, 'aoe', '啊啊啊！', 'yell'),
(NULL, 'aoe', '利若伊！詹金斯！', 'yell'),
(NULL, 'aoe', '好的。我们在群体攻击方面有什么呢？', 'say'),
(NULL, 'aoe', '这变得有趣了。', 'say'),
(NULL, 'aoe', '酷。把他们集中在一个地方，来一个好的火焰冲击。', 'say'),
(NULL, 'aoe', '杀！杀！杀！', 'say'),
(NULL, 'aoe', '我觉得我的裤子湿了。', 'say'),
(NULL, 'aoe', '我们成为历史了。', 'say'),
(NULL, 'aoe', '我希望治疗者们准备好了。李尔罗伊！', 'say'),
(NULL, 'aoe', '我希望他们不会来找我。', 'say'),
(NULL, 'aoe', '哦，不。在这场屠杀中我什么都看不见。', 'say');

INSERT INTO `playerbots_speech` VALUES
(NULL, 'loot', '我希望会有一些钱。', 'say'),
(NULL, 'loot', '抢战利品！抢战利品！', 'say'),
(NULL, 'loot', '我的宝贝。', 'say'),
(NULL, 'loot', '我希望那里有一个闪亮的史诗物品在等我。', 'say'),
(NULL, 'loot', '我有很深的口袋和包。', 'say'),
(NULL, 'loot', '一切都是我的！', 'say'),
(NULL, 'loot', '希望今天没有灰色垃圾。', 'say'),
(NULL, 'loot', '这些战利品是我的！', 'say'),
(NULL, 'loot', '抢劫很恶心，但我需要钱。', 'say'),
(NULL, 'loot', '金子！', 'say'),
(NULL, 'loot', '好的。让我们看看他们有什么。', 'say'),
(NULL, 'loot', '别担心。我会抢走一切。', 'say'),
(NULL, 'loot', '我是抢劫忍者。', 'say'),
(NULL, 'loot', '我需要掷骰子吗？', 'say'),
(NULL, 'loot', '有人能给我解释一下，他们把这些东西都放在哪里了？', 'say'),
(NULL, 'loot', '不，我不会抢灰色垃圾。', 'say'),
(NULL, 'loot', '我是第一个。我是第一个。我是第一个。', 'say'),
(NULL, 'loot', '把你的钱给我！', 'say'),
(NULL, 'loot', '我的口袋是空的，我需要装满它们。', 'say'),
(NULL, 'loot', '我为此准备了一个新包。', 'say'),
(NULL, 'loot', '我希望在抢劫的时候不会吸引到任何人。', 'say'),
(NULL, 'loot', '请别看。我在抢劫。', 'say'),
(NULL, 'loot', '哈！你一点都得不到！', 'say'),
(NULL, 'loot', '抢劫很酷。', 'say'),
(NULL, 'loot', '我喜欢新装备。', 'say'),
(NULL, 'loot', '如果再没有有价值的东西我就退出。', 'say'),
(NULL, 'loot', '我希望是一个漂亮的戒指。', 'say'),
(NULL, 'loot', '我会从你那里抢走战利品。', 'say'),
(NULL, 'loot', '大家都离远点。我要去抢劫了。', 'say'),
(NULL, 'loot', '甜蜜的战利品。', 'say'),
(NULL, 'loot', '掷骰子之神！今天给我一个史诗物品。', 'say'),
(NULL, 'loot', '请给我新玩具。', 'say'),
(NULL, 'loot', '我希望他们带着好吃的。', 'say'),
(NULL, 'loot', '金子是我的。我保证我会留下其他东西。', 'say'),
(NULL, 'loot', '不，我无法抗拒。', 'say'),
(NULL, 'loot', '我想要更多！', 'say');

INSERT INTO `playerbots_speech` VALUES
(NULL, 'low ammo', '我只剩下一点 <弹药> 了！', 'say'),
(NULL, 'low ammo', '我需要更多 <ammo>！', 'say'),
(NULL, 'low ammo', '还剩 100 <ammo>！', 'say'),
(NULL, 'no ammo', '就这样！没有 <ammo> 了！', 'say'),
(NULL, 'no ammo', '还有你拿着我的弓…… 哎呀，没有 <ammo> 了！', 'say'),
(NULL, 'no ammo', '需要弹药！', 'yell');